### PR TITLE
Smartfetch: decreases footprint, increases speed.

### PR DESCRIPTION
**Pull request by C-P-949**
For your consideration, I present the smartfetch option.
On my last engagement this increased overall speed of httpscreenshot by ~~44%~~ 34% (10 workers, ~7500 urls, with vhost discovery).

In short, it hashes the HTML content of each page retrieved by doGet, checks to see if that hash already exists, if it does not, the worker makes note of the hash and  continues to grab the page screenshot and .HTML with selenium

But, If the hash already exists, that means we already have a screenshot and .HTML file that matches this page, instead of grabbing them again, we can just copy the files locally.

If the fuzzy matching was added from cluster.py, I'm willing to bet we could drive the network footprint lower, and further increase speed. But that's for later, this PR was the immediately obvious speed increase. 

Also, I added some code legibility enhancements, and what I consider a few minor optimizations, feel free to ignore them.

### CODE REVIEW

**Comment by C-P-949** [comment]
Try it out with -sF or --smartfetch, everything else is the same.

**Comment by jstnkndy** [comment]
Great idea, code looks good, we'll run it through some tests. Thanks for the PR!

**Comment by C-P-949** [comment]
I managed to find my notes and some numbers from some tests I ran a week or so ago,  with and without smartfetch enabled.

sf

**Comment by breenmachine** [comment]
Thanks a lot for this addition, it's great! I look forward to trying it out in real life on our next big network assessment.

**Comment by C-P-949** [comment]
Glad to help!

Funny story, I was working on a tool exactly the same as httpscreenshot, I later found out you folks already released. We had essentially the same ideas for overall logic, so I started comparing notes.

I'm working on some other improvements for both our projects that could provide even more speed improvements. I'll send another PR if I am successful.

**Pull request merged**
