### PR TITLE
Python 3 and more

### PR DESCRIPTION
**Pull request by jesse-osiecki**
Remove PhantomJS
Default to Firefox
Convert code to work with Python3
Run Black and yapf against source file
Update Dockerfile to use ubuntu 20.04 and apt geckodriver, fix dependencies

### CODE REVIEW

**Comment by breenmachine** [comment]
Thanks so much! I've been meaning to fix this code for ages and haven't gotten around to it. I'll test and merge this tomorrow.

**Comment by jesse-osiecki** [comment]
It’s the least I could do! It’s been very useful lately. Please let me know if anything is broken and needs changes, but “it works for me”

—
Jesse

**Comment by jesse-osiecki** [comment]
I'm adding a few more things today, the socket library was missing in imports, masscan xml support (hopefully), among other things

**Comment by breenmachine** [comment]
Had some time to try it out and looks good! The cluster script needs some updates as well but I'll take care of that. Thanks again!

**Comment by jesse-osiecki** [comment]
If you want any help let me know, I’d be happy to assist 

—
Jesse

**Pull request merged**
